### PR TITLE
fixed to handle new parameter force_insertion

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Comment by valearna** [comment]
Thanks @sweng66 , I'll defer to @pjhale since he's working on changes that use the 'force insertion' option

**Comment by sweng66** [comment]
Okay thanks @valearna

**Comment by pjhale** [comment]
This should be fine... just to be clear I should still pass the curie with an additional JSON parameter "force_insertion: true".  Correct?  With the curator function I think we always want to force the insertion.

**Comment by sweng66** [comment]
Currently, API will check if the tag row has force_insertion passed in (along with the reference curie), if yes and it is true, then it will not check for duplicate tag row(s), instead it will insert the new row into the database directly. 

I don't really know what you are using the force_insertion parameter for so I have no idea if my fix will affect your work or not. @pjhale 

We can talk about it at standup.

**Review by valearna — APPROVED** [review]

**Comment by sweng66** [comment]
Thanks @valearna

**Pull request merged**
