### PR TITLE
Do not load mappings on page changes

### PR DESCRIPTION
**Pull request by valearna**
Also added missing dependency on fontawesome icons

### CODE REVIEW

**Review by sweng66 — APPROVED** [review]
Thanks @valearna

**Review by azurebrd — COMMENTED** [review]
@valearna Why did the package.json change without new font awesome change in the code ?

**Comment by sweng66** [comment]
Not sure why stage was working without @fortawesome/free-regular-svg-icons.

In my sandbox, dev3006 didn't work before installing fortawesome/free-regular-svg-icons

**Comment by azurebrd** [comment]
Ah, I see, thanks @sweng66

**Pull request merged**
