### PR TITLE
Scrum 2767 - Updated UI dependencies

### PR DESCRIPTION
**Pull request by valearna**
- Updated React and React scripts. Now the app reloads automatically on code changes.
- Updated date picker version (the old one was not working with the latest version of React) - @pjhale everything seems ok to me but it would be great if you could take a look
- Replaced loading overlay with custom css. This resolved some dependency issues. Now when facets are loading the overlay is applied to the whole page. We also created a new component to activate the overlay. Thanks @azurebrd and @sweng66 for your help!

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Thanks @valearna !

**Comment by pjhale** [comment]
Date picker is working fine and so is the general interface but I'm getting a ton of webpack warnings that weren't there before... like this one

WARNING in ./node_modules/@okta/okta-signin-widget/dist/css/okta-sign-in.min.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/@okta/okta-signin-widget/dist/css/okta-sign-in.min.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/root/okta/okta-signin-widget/target/sass/widgets/_mega-drop-down.scss' file: Error: ENOENT: no such file or directory, open '/root/okta/okta-signin-widget/target/sass/widgets/_mega-drop-down.scss'

Is it possible there is a file not included in the PR?

**Comment by valearna** [comment]
Thanks @pjhale, I'll take a look

**Comment by valearna** [comment]
@pjhale I pushed a fix for the source map warnings. These were introduced by the new version of react-scripts. Unfortunately the only solution I found is to ignore the warnings using an alternative react-scripts command that can be configured to ignore specific warnings. Let me know if this looks ok to you.

**Pull request merged**
