### PR TITLE
feat(search): added new 'ID' search field

### PR DESCRIPTION
**Pull request by valearna**
- unified search interface for xrefs and title searches with new search field 'ID'
- when searching for an AGR curie (starting with AGR: or AGRKB:) clicking the search button automatically redirects to the biblio edit page for the inserted curie
- other IDs are managed using functions from the old xref query form and if the xref is found the page redirects to the biblio edit with the respective agr curie

### CODE REVIEW

**Comment by valearna** [comment]
@pjhale I've unified the search interfaces but kept the old functions for searching xrefs. I've added a special case for AGR curies that redirects directly to the biblio edit page. After talking to Ceri I realized that there's no need to use elasticsearch for these searches as we don't need to search for obsolete xrefs or curies

**Review by azurebrd — APPROVED** [review]
That's great, thanks @valearna 

In components/search/Facets.js line 155-7 I understand that it makes sense, but it's a bit confusing without { } or indentation that 156 is the then part, or just removing the if in 155 and making an && to connect to line 156.  It's find though.

searchActions line 75-79 indentation is the same as before, so it's fine, but it's also a bit off.

**Comment by valearna** [comment]
Thanks @azurebrd! 

I've added {} and fixed indentation in Facets.js for lined 155-7.

In searchActions the indentation looks off, but it's what pycharm is applying for standard js code, so I'd keep it as is

**Review by azurebrd — APPROVED** [review]
Thanks @valearna !

Oh, interesting about how pycharm does it.  Good to know :)

**Pull request closed without merging**
