### PR TITLE
added code to force the page to reload after adding or updating a lic…

### PR DESCRIPTION
**Pull request by sweng66**
…ense

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
I'll defer to @valearna here, I think he's done most of the FileManagement before ?  I'm not sure we want to reload, which might update what's in the redux store, or change the location in the page the user is viewing (I'm not sure it does either thing), as opposed to just doing an API call to get whatever could have been updated.

**Comment by valearna** [comment]
@azurebrd I was thinking about the same thing, we should try to reload the data from the api instead of reloading the whole page, but this is ok if we need a quick and dirty solution for now

**Comment by sweng66** [comment]
Makes sense! Thanks @azurebrd @valearna 

I will play around with api reloading and will ask for help if needed.

**Comment by sweng66** [comment]
Will merge this change to main first and then fix it to reload the data from API.

**Pull request merged**
