### PR TITLE
feat(topic_entity_tag): new icons for sorting

### PR DESCRIPTION
**Pull request by valearna**
Clicking three times goes back to non-sorted results

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Cool !  I think it does a 3 way toggle between not / down / up ?  But there's only an up and down icon, and not a sort icon for the not state ?

**Comment by valearna** [comment]
Yes, I couldn't find the double icon arrow and I set the down arrow (not colored) as default, but I can add the default sort icon if we find it

**Comment by azurebrd** [comment]
Gotcha, cool

**Comment by valearna** [comment]
I found the icons in font awesome, but not in react icons (which is supposed to be a meta project containing also fa icons). I'll update them

**Pull request merged**
