### PR TITLE
adding code to send an alert when an invalid curie or XREF ID is entered for biblio se…

### PR DESCRIPTION
**Pull request by sweng66**
…arch/editor pages

### CODE REVIEW

**Review by azurebrd — CHANGES_REQUESTED** [review]
Since you're importing the Alert component, could you use it instead of a <div> ?

Like 
ATeamAlert.js:            <Alert className="ateam-alert" variant="danger" onClose={() => setStatus(true)} dismissible>
ATeamAlert.js:                <Alert.Heading>Looks like {ateamApiBaseUrl} is down</Alert.Heading>
ATeamAlert.js:            </Alert>

Which lets you set "dismissable" so curators can close the alert by clicking the x

**Comment by sweng66** [comment]
Cool @azurebrd Will fix

**Review by azurebrd — APPROVED** [review]
Great, thanks @sweng66 !

**Comment by sweng66** [comment]
Cool. Thanks @azurebrd

**Pull request merged**
