### PR TITLE
Scrum 2912 sort retrieve referencefile

### PR DESCRIPTION
**Pull request by FB-ping**

### CODE REVIEW

**Review by valearna — CHANGES_REQUESTED** [review]
It looks like there are conflicts to be resolved in the Sort.js component. Can you resolve them and push again @FB-ping ?

**Comment by FB-ping** [comment]
@valearna I solved the conflict online, but then I git pull to update my local, some error happen with components/biblio, which I didn't touch.  see   https://dev3005.alliancegenome.org/sort , maybe I should re-start my UI ?

**Comment by valearna** [comment]
Yes, try to restart your instance

**Comment by FB-ping** [comment]
@valearna just try, with this error: Module not found: Error: Can't resolve 'react-bootstrap-typeahead' in '/home/pzhou/alliance/agr_literature_ui/src/components/biblio

**Comment by FB-ping** [comment]
Module not found: Error: Can't resolve 'react-bootstrap-typeahead' in '/home/pzhou/alliance/agr_literature_ui/src/components/biblio'
ERROR in ./src/components/biblio/BiblioEntity.js 28:0-59

**Review by azurebrd — APPROVED** [review]
This looks good to me, @FB-ping but we shouldn't merge this until the related API changes are deployed on stage, otherwise this will break the Sort page on stage UI.

**Comment by azurebrd** [comment]
@FB-ping Valerio installed a new package for the UI, so you have to rm -rf node_modules/ and npm install

**Comment by valearna** [comment]
yes, run `npm install` before restarting

**Comment by FB-ping** [comment]
@valearna @azurebrd I do those steps:
rm -rf node_modules/
   npm install -g n
   nvm install 12.22.7
   nvm use 12.22.7
   npm start

then got error:
ERROR: npm v9.6.7 is known not to run on Node.js v12.22.7.  This version of npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/home/pzhou/.nvm/versions/node/v12.22.7/lib/node_modules/npm/lib/utils/exit-handler.js:19
  const hasLoadedNpm = npm?.config.loaded

**Comment by azurebrd** [comment]
@FB-ping I don't know why you're doing the nvm steps.  I think what I said before "rm -rf node_modules/ and npm install" then npm start should work.  I also don't know what -g n does.

**Pull request closed without merging**
