### PR TITLE
Adding 'delete' button to the rows that login user has permission to delete in the Topic/Entity Editor

### PR DESCRIPTION
**Pull request by sweng66**

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Thanks @sweng66 !

The console errors might be better as modal messages, and might want curator feedback on that.

Xenbase and XB sometimes need to be handled differently, but if you tested the XB case and it works, that's great.  (like, not sure if the lookup works, or what the accessLevel is, I imagine it's all XB for okta accessLevel + modCurie in db, but just in case one of them is 'Xenbase')

**Comment by sweng66** [comment]
Good point about XB! will test

**Comment by sweng66** [comment]
It works for XB too! Thanks @azurebrd

**Comment by azurebrd** [comment]
cool @sweng66 !

**Pull request merged**
