### PR TITLE
SCRUM-1770 Adding Extra Fields to search results

### PR DESCRIPTION
**Pull request by pjhale**
Added xRefs, Authors, pub date, and abstract.  Needs the corresponding 
pr in the API to have access to this data.  Adds red obsolete to 
obsolete xrefs and cuts abstracts down to 500 chars.

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
Hi @pjhale .  The .Col-general is used a lot in the Biblio section.  If I could see how that looks and it generally looks the same, then display: block sounds good.  But if it doesn't, we might want a different css entry for the Search page to use

**Comment by pjhale** [comment]
Changed it so it has its own class for the block style... everything else from col-general looks good there.

**Review by azurebrd — APPROVED** [review]
Cool, if that works for you, that's great @pjhale 
I don't recall how .css inheritance works if there's 2 classes that set the same field to different values (Col-general display-> flex, Col-search display->block, new Col in line 28 with both classNames)  I think for equal specificity, what takes precedence is what order they show up in the .css file with the later values taking precedence, but if you know for sure, let me know :)

**Comment by azurebrd** [comment]
@pjhale From the comment about the API PR, I'm not sure if this is ready to merge.  I think the moment it merges, @valearna set it so that it will update stage-literature UI to run that code, so if it's dependent on the API PR we could just leave this ready to Merge.

**Comment by pjhale** [comment]
This needs the following API PR to work properly...  let me know if there is a better way to link these PR's....

https://github.com/alliance-genome/agr_literature_service/pull/222

**Pull request merged**
