### PR TITLE
Scrum 2912 sort retrieve referencefile

### PR DESCRIPTION
**Pull request by FB-ping**
UI can display multiple main file for sort, see  https://dev3005.alliancegenome.org/sort, try "FB" with referencefile records.

### CODE REVIEW

**Review by azurebrd — APPROVED** [review]
Thanks @FB-ping .  I can't tell what's different from the previous PR, but if it basically does the same and fixes the warnings, then great.

Edit : Also, I don't know if the corresponding API PR was merged, but if it wasn't, then merging this will break the Sort page.

**Comment by FB-ping** [comment]
@azurebrd this PR will display the referencefile with multiple main files.  yes, need to wait @valearna to review the API PR https://github.com/alliance-genome/agr_literature_service/pull/426 before we can merge this into main.

**Comment by azurebrd** [comment]
@FB-ping I don't think @valearna will check PRs until he's back on the 15th.  I think he said that it was okay to merge and there'd be a rework in the future ?

**Comment by azurebrd** [comment]
Oh, you already merged the API, great, thanks.

**Pull request merged**
