### PR TITLE
change display to show date_last_modified_in_pubmed and date_arrived_…

### PR DESCRIPTION
**Pull request by azurebrd**
…in_pubmed in a row, and date_last_modified_in_pubmed and date_created in another row

### CODE REVIEW

**Review by valearna — COMMENTED** [review]
The two components look very similar, at least the jsx part. Can we create a single parametrized component instead of two?

**Comment by azurebrd** [comment]
@valearna They're very similar, but in the BiblioDisplay section, I want to be able to switch without processing the data, and each of the components that get called there have a different way of processing.  I don't know what happened to the BiblioEditor changes, they should be part of this PR too, and they mostly mirror each other.  I think it's clearer to have the processing in each component instead of the parent component.  In the BiblioEditor, the updateFlag colours usually need processing too, but these two fields just happen to be display-only, so they don't need that logic, but in general we can't have a display of paired data, since those will need the updateFlag colour logic.  It seemed clearer to just make similar pairs of components

**Comment by azurebrd** [comment]
@valearna I don't know how these BiblioEditor changes got into main, but they're here https://github.com/alliance-genome/agr_literature_ui/blob/main/src/components/biblio/BiblioEditor.js#L519  The Display part just mirrors that for consistency.

**Comment by valearna** [comment]
Sounds good @azurebrd

**Review by valearna — APPROVED** [review]

**Comment by azurebrd** [comment]
Thanks @valearna !

**Pull request merged**
